data:
  root_folder: ./data
  force_download: false
  n_views: 2

arch: resnet18
out_dim: 128

learning_rate: 0.0003
weight_decay: 1.0e-4
batch_size: 512
epochs: 100
num_workers: 0

fp16_precision: false
log_every_n_steps: 100
temperature: 0.07

seed: 42
